# Generated by Django 4.0.3 on 2022-03-31 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Наименование')),
                ('floor', models.PositiveIntegerField(blank=True, verbose_name='Этаж')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Автозал',
                'verbose_name_plural': 'Автозалы',
                'db_table': 'cas',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, choices=[('active', 'Активное оборудование'), ('passive', 'Пассивное оборудование')], max_length=100, verbose_name='Тип оборудования')),
                ('place', models.CharField(max_length=5, verbose_name='Место')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Модель')),
                ('owner', models.CharField(max_length=50, verbose_name='Владелец')),
                ('desc', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('port_cnt', models.PositiveIntegerField(verbose_name='Количество портов')),
                ('port_prefix', models.CharField(max_length=10, verbose_name='Префикс порта')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('manager', models.CharField(max_length=30, verbose_name='Ответственный')),
                ('cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='main.cas', verbose_name='Автозал')),
            ],
            options={
                'verbose_name': 'Стойка',
                'verbose_name_plural': 'Стойки',
                'db_table': 'rack',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(verbose_name='№ порта')),
                ('desc', models.CharField(max_length=200, verbose_name='Описание')),
                ('dest', models.CharField(max_length=50, verbose_name='Направление')),
                ('commId', models.CharField(max_length=50, verbose_name='ID коммутации')),
                ('busy', models.BooleanField(default=False, verbose_name='Порт занят')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='main.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Порт',
                'verbose_name_plural': 'Порты',
                'db_table': 'port',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='main.rack', verbose_name='Стойка'),
        ),
        migrations.CreateModel(
            name='Commutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, verbose_name='Описание')),
                ('full_path', models.CharField(default='-', max_length=100, verbose_name='Полный путь')),
                ('from_equip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_equip', to='main.equipment', verbose_name='Оборудование откуда')),
                ('from_port', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_port', to='main.port', verbose_name='Порт откуда')),
                ('from_rack', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_rack', to='main.rack', verbose_name='Стойка откуда')),
                ('to_equip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_equip', to='main.equipment', verbose_name='Оборудование куда')),
                ('to_port', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_port', to='main.port', verbose_name='Порт куда')),
                ('to_rack', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_rack', to='main.rack', verbose_name='Стойка куда')),
            ],
            options={
                'verbose_name': 'Коммутация',
                'verbose_name_plural': 'Коммутации',
                'db_table': 'commutation',
            },
        ),
    ]
