# Generated by Django 4.0.3 on 2022-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_equipment_port_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='manager',
        ),
        migrations.AddField(
            model_name='cas',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
