# Generated by Django 4.0.3 on 2022-03-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_rack_manager_cas_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cas',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
