# Generated by Django 4.0.3 on 2022-03-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cas_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cas',
            new_name='Caz',
        ),
        migrations.RenameField(
            model_name='rack',
            old_name='cas',
            new_name='caz',
        ),
    ]
