# Generated by Django 4.0.3 on 2022-03-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_cas_caz_rename_cas_rack_caz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caz',
            new_name='Autozal',
        ),
        migrations.RenameField(
            model_name='rack',
            old_name='caz',
            new_name='autozal',
        ),
    ]
