# Generated by Django 4.0.3 on 2022-04-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_rack_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='model',
        ),
    ]
