# Generated by Django 4.0.3 on 2022-04-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_equipment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autozal',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='place',
            field=models.CharField(max_length=5, unique=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер'),
        ),
    ]
