# Generated by Django 4.0.3 on 2022-04-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_autozal_slug_alter_equipment_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(blank=True, choices=[('', 'Выберите тип...'), ('active', 'Активное оборудование'), ('passive', 'Пассивное оборудование')], max_length=100, verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='place',
            field=models.CharField(max_length=5, verbose_name='Место'),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('rack', 'place')},
        ),
    ]
