# Generated by Django 4.0.3 on 2022-04-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_equipment_equipment_type_alter_equipment_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='port_type',
            field=models.CharField(blank=True, choices=[('', 'Выберите тип...'), ('access', 'A'), ('trunk', 'T')], max_length=100, verbose_name='Тип оборудования'),
        ),
    ]
