# Generated by Django 4.0.3 on 2022-04-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_port_port_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Порт занят'),
        ),
        migrations.AddField(
            model_name='port',
            name='vlan',
            field=models.CharField(default=999, max_length=100, verbose_name='Vlan'),
        ),
        migrations.AlterField(
            model_name='port',
            name='port_type',
            field=models.CharField(choices=[('', 'Выберите тип...'), ('access', 'Access'), ('trunk', 'Trunk')], default='access', max_length=6, verbose_name='Тип порта'),
        ),
    ]
