# Generated by Django 4.0.3 on 2022-04-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_port_active_port_vlan_alter_port_port_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='port_type',
            new_name='type',
        ),
    ]
