# Generated by Django 4.0.3 on 2022-04-08 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_equipment_type_equipment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commutation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commutation',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлен'),
        ),
        migrations.AlterField(
            model_name='port',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Порт включен'),
        ),
    ]
