# Generated by Django 4.0.3 on 2022-04-11 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_commutation_created_commutation_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.AlterField(
            model_name='port',
            name='dest',
            field=models.CharField(max_length=50, verbose_name='Куда'),
        ),
        migrations.AddField(
            model_name='port',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='main.category', verbose_name='Категория'),
        ),
    ]
