# Generated by Django 4.0.3 on 2022-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='type',
            field=models.CharField(default='access', max_length=6, verbose_name='Тип порта'),
        ),
    ]
