# Generated by Django 4.0.3 on 2022-04-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_port_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commutation',
            name='from_equip',
        ),
        migrations.RemoveField(
            model_name='commutation',
            name='from_rack',
        ),
        migrations.AlterField(
            model_name='commutation',
            name='from_port',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_port', to='main.port', verbose_name='Откуда'),
        ),
    ]
