# Generated by Django 4.0.3 on 2022-04-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_commutation_from_equip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='commId',
        ),
        migrations.RemoveField(
            model_name='port',
            name='dest',
        ),
        migrations.AlterField(
            model_name='commutation',
            name='from_port',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='main.port', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='commutation',
            name='to_equip',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_equip', to='main.equipment', verbose_name='Оборудование куда'),
        ),
        migrations.AlterField(
            model_name='commutation',
            name='to_port',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_port', to='main.port', verbose_name='Порт куда'),
        ),
        migrations.AlterField(
            model_name='commutation',
            name='to_rack',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_rack', to='main.rack', verbose_name='Стойка куда'),
        ),
    ]
