# Generated by Django 4.0.3 on 2022-04-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_port_commid_remove_port_dest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commutation',
            old_name='to_equip',
            new_name='dest_equip',
        ),
        migrations.RenameField(
            model_name='commutation',
            old_name='to_port',
            new_name='dest_port',
        ),
        migrations.RenameField(
            model_name='commutation',
            old_name='to_rack',
            new_name='dest_rack',
        ),
        migrations.RenameField(
            model_name='commutation',
            old_name='from_port',
            new_name='source_port',
        ),
        migrations.RemoveField(
            model_name='port',
            name='desc',
        ),
    ]
