# Generated by Django 4.0.3 on 2022-04-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_to_equip_commutation_dest_equip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commutation',
            name='dest_equip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_equip', to='main.equipment', verbose_name='Оборудование куда'),
        ),
        migrations.AlterField(
            model_name='commutation',
            name='dest_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_port', to='main.port', verbose_name='Порт куда'),
        ),
        migrations.AlterField(
            model_name='commutation',
            name='dest_rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_rack', to='main.rack', verbose_name='Стойка куда'),
        ),
        migrations.AlterField(
            model_name='commutation',
            name='source_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='main.port', verbose_name='Откуда'),
        ),
    ]
