# Generated by Django 4.0.3 on 2022-04-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_commutation_source_equip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commutation',
            name='dest_equip',
        ),
        migrations.RemoveField(
            model_name='commutation',
            name='dest_rack',
        ),
        migrations.RemoveField(
            model_name='commutation',
            name='source_equip',
        ),
        migrations.RemoveField(
            model_name='commutation',
            name='source_rack',
        ),
        migrations.AlterField(
            model_name='commutation',
            name='dest_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_port', to='main.port', verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='commutation',
            name='source_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_port', to='main.port', verbose_name='Откуда'),
        ),
    ]
