# Generated by Django 4.0.3 on 2022-04-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_port_commutation_alter_commutation_dest_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commutation',
            name='dest_port',
            field=models.CharField(blank=True, default='-', max_length=10, verbose_name='Куда'),
        ),
    ]
