# Generated by Django 4.0.3 on 2022-04-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_port_dest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commutation',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='commutation',
            name='full_path',
        ),
        migrations.AddField(
            model_name='port',
            name='desc',
            field=models.CharField(default='-', max_length=100, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='port',
            name='full_path',
            field=models.CharField(default='-', max_length=100, verbose_name='Полный путь'),
        ),
    ]
