# Generated by Django 4.0.3 on 2022-04-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_port_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='desc',
            field=models.CharField(default='-', max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='port',
            name='dest',
            field=models.CharField(default='-', max_length=100, null=True, verbose_name='Куда'),
        ),
    ]
