# Generated by Django 4.0.3 on 2022-04-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_port_dest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='commutation',
        ),
    ]
