# Generated by Django 4.0.3 on 2022-04-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_port_dest_id_port_dest_port_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='full_path',
            field=models.CharField(default='-', max_length=100, null=True, verbose_name='Полный путь'),
        ),
    ]
