# Generated by Django 4.0.3 on 2022-04-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_port_full_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='full_path',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='Полный путь'),
        ),
    ]
