# Generated by Django 4.0.3 on 2022-04-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_port_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='dest',
            field=models.CharField(blank=True, max_length=100, verbose_name='Куда'),
        ),
    ]
