# Generated by Django 4.0.3 on 2022-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_vlantoport_alter_vlan_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='desc',
            field=models.TextField(blank=True, default='-', max_length=200, verbose_name='Описание'),
        ),
    ]
