# Generated by Django 4.0.3 on 2022-04-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_vlan_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlan',
            name='desc',
        ),
    ]
