# Generated by Django 4.0.3 on 2022-04-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_vlan_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='vlan',
        ),
        migrations.AddField(
            model_name='port',
            name='vlan',
            field=models.ManyToManyField(to='main.vlan'),
        ),
    ]
