# Generated by Django 4.0.3 on 2022-04-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_port_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='type',
            field=models.CharField(choices=[('', 'Выберите тип...'), ('access', 'Access'), ('trunk', 'Trunk')], default='access', max_length=6, verbose_name='Тип порта'),
        ),
    ]
