# Generated by Django 4.0.3 on 2022-04-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_port_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='vlan',
            field=models.ManyToManyField(blank=True, to='main.vlan'),
        ),
    ]
