# Generated by Django 4.0.3 on 2022-05-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_port_vlan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VlanToPort',
        ),
    ]
