# Generated by Django 4.0.3 on 2022-05-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_delete_vlantoport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='port_cnt',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Выберите тип...'), ('active', 'Активное оборудование'), ('passive', 'Пассивное оборудование'), ('unmanageable', 'Неуправляемое оборудование'), ('server', 'Сервер'), ('operator', 'Оборудование оператора связи')], max_length=100, verbose_name='Тип оборудования'),
        ),
    ]
