# Generated by Django 4.0.3 on 2022-05-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_remove_equipment_port_cnt_alter_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='port_cnt',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество портов'),
        ),
    ]
