# Generated by Django 4.0.3 on 2022-05-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_equipment_port_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='port_cnt',
            field=models.PositiveIntegerField(verbose_name='Количество портов'),
        ),
    ]
