# Generated by Django 4.0.3 on 2022-05-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_equipment_desc_alter_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='desc',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
