# Generated by Django 4.0.3 on 2022-05-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_port_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='prefix',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Префикс порта'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Выберите тип...'), ('active', 'Активное оборудование'), ('passive', 'Пассивное оборудование'), ('server', 'Сервер'), ('unmanageable', 'Неуправляемое оборудование'), ('operator', 'Оборудование оператора связи')], max_length=100, verbose_name='Тип оборудования'),
        ),
    ]
