# Generated by Django 4.0.3 on 2022-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_equipment_prefix_alter_equipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='num',
        ),
        migrations.AddField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Наименование порта'),
        ),
    ]
