# Generated by Django 4.0.3 on 2022-05-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_remove_port_num_port_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='num',
            field=models.PositiveIntegerField(null=True, verbose_name='№ порта'),
        ),
    ]
