# Generated by Django 4.0.3 on 2022-05-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_port_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='num',
        ),
    ]
