# Generated by Django 4.0.3 on 2022-05-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_remove_port_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер порта'),
        ),
    ]
