# Generated by Django 4.0.3 on 2022-05-16 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_port_desc_alter_port_dest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование интерфеса')),
                ('ip', models.CharField(max_length=50, verbose_name='IP интерфеса')),
                ('mask', models.CharField(blank=True, max_length=50, null=True, verbose_name='Маска подсети')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Security level')),
                ('gateway', models.CharField(blank=True, max_length=50, null=True, verbose_name='GW интерфеса')),
                ('desc', models.TextField(blank=True, default='-', max_length=500, verbose_name='Описание')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface', to='main.port', verbose_name='Порт')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface', to='main.vlan', verbose_name='Vlan')),
            ],
            options={
                'verbose_name': 'Интерфес',
                'verbose_name_plural': 'Интерфесы',
                'db_table': 'interface',
            },
        ),
    ]
