# Generated by Django 4.0.3 on 2022-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='management',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP управления'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Выберите тип...'), ('switch', 'Коммутатор'), ('router', ' Маршрутизатор'), ('server', 'Сервер'), ('cross', 'Кросс'), ('patсh-panel', 'Патч-панель'), ('unmanageable', 'Неуправляемое оборудование'), ('operator', 'Оборудование оператора связи')], max_length=100, verbose_name='Тип оборудования'),
        ),
    ]
